apiVersion: v2
name: myapp
description: A simple Helm chart for risk pipeline testing
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: redis
    version: "22.0.3"
    repository: "https://charts.bitnami.com/bitnami"
  - name: postgresql
    version: "16.7.26"
    repository: "https://charts.bitnami.com/bitnami"
  - name: mysql
    version: "14.0.3"
    repository: "https://charts.bitnami.com/bitnami"
