apiVersion: v2
name: myapp
description: A simple Helm chart for risk pipeline testing
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: redis
    version: "21.1.10"
    repository: "https://charts.bitnami.com/bitnami"

