name: Helm Chart Security and Risk Scan

on:
  pull_request:
    branches: [ "*" ]

jobs:
  scan-redis-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Syft
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | bash -s -- -b /usr/local/bin

      - name: Install Trivy
        run: curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Install Python dependencies
        run: pip install epss-api cvss

      - name: Install jq (for JSON formatting)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Find modified Helm chart directories
        id: charts
        run: |
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          git fetch origin $BASE_BRANCH
          dirs=$(git diff --name-only origin/$BASE_BRANCH...HEAD | grep '^charts/.*/Chart.yaml' | xargs -r -n1 dirname | uniq)
          echo "dirs=$dirs" >> $GITHUB_OUTPUT

      - name: Scan Redis image(s) from Chart.yaml
        if: ${{ steps.charts.outputs.dirs != '' }}
        run: |
          dirs="${{ steps.charts.outputs.dirs }}"
          for CHART in $dirs
          do
            # Extract Redis version from dependencies in Chart.yaml
            REDIS_VER=$(awk '/- name: redis/,/version:/' "$CHART/Chart.yaml" | grep version | head -1 | awk '{print $2}' | tr -d '"')
            if [ -z "$REDIS_VER" ]; then
              echo "No Redis version found in $CHART/Chart.yaml, skipping."
              continue
            fi

            echo "Scanning bitnami/redis:$REDIS_VER referenced in $CHART"
            # Run Trivy image scan
            trivy image --severity HIGH,CRITICAL --format json bitnami/redis:$REDIS_VER > "trivy-redis-${REDIS_VER}.json"
            cat "trivy-redis-${REDIS_VER}.json"

            # Risk scoring (adjust path to your script!)
            python3 scripts/score.py "trivy-redis-${REDIS_VER}.json" > "risk-redis-${REDIS_VER}.txt"
            cat "risk-redis-${REDIS_VER}.txt"
          done

      - name: Comment Trivy scan & risk score on PR
        if: ${{ steps.charts.outputs.dirs != '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dirs="${{ steps.charts.outputs.dirs }}"
          for CHART in $dirs
          do
            REDIS_VER=$(awk '/- name: redis/,/version:/' "$CHART/Chart.yaml" | grep version | head -1 | awk '{print $2}' | tr -d '"')
            if [ -z "$REDIS_VER" ]; then
              continue
            fi
            MSG="## Trivy Results for Redis $REDIS_VER (referenced in $CHART)\n"
            MSG+="\n\`\`\`\n$(jq '.Results' trivy-redis-${REDIS_VER}.json)\n\`\`\`"
            MSG+="\n\n## Risk Score\n"
            MSG+="\n\`\`\`\n$(cat risk-redis-${REDIS_VER}.txt)\n\`\`\`"
            gh pr comment ${{ github.event.pull_request.number }} --body "$MSG"
          done

      - name: Upload Trivy scan results
        if: ${{ steps.charts.outputs.dirs != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results
          path: trivy-redis-*.json

      - name: Upload risk score results
        if: ${{ steps.charts.outputs.dirs != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: risk-results
          path: risk-redis-*.txt
