name: risk-score
on:
  workflow_run:
    workflows: ["build-sbom"]
    types: [completed]
jobs:
  score:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: trivy-scan
      - uses: actions/checkout@v4
      - name: Install Python packages
        run: pip install epss-api cvss
      - name: Compute Risk Score
        run: python scripts/score.py trivy.json > risk.txt
      - name: Comment on PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr comment ${{ github.event.workflow_run.pull_requests.number }} --body "$(cat risk.txt)"
