name: sbom-plus-risk
on:
  pull_request:
    branches: [ main ]
jobs:
  sbom_and_risk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | bash -s -- -b /usr/local/bin

      - name: Generate SBOM (SPDX JSON)
        # For demo/testing, scan nginx; change to your real app/image as needed
        run: syft nginx:latest -o spdx-json > sbom.spdx.json

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Scan SBOM with Trivy
        run: trivy sbom sbom.spdx.json --format json > trivy.json

      - name: Install Python packages
        run: pip install epss-api cvss

      - name: Compute Risk Score
        run: python scripts/score.py trivy.json > risk.txt

      - name: Comment on PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr comment ${{ github.event.pull_request.number }} --body "$(cat risk.txt)"

      - name: Upload Trivy Result
        uses: actions/upload-artifact@v4
        with:
          name: trivy-result
          path: trivy.json

      - name: Upload Risk Score
        uses: actions/upload-artifact@v4
        with:
          name: risk-result
          path: risk.txt

