name: build-sbom
on:
  pull_request:
    branches: [ main ]
jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | bash -s -- -b /usr/local/bin

      - name: Generate SBOM (SPDX JSON)
        run: syft dir:. -o spdx-json > sbom.spdx.json

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Scan SBOM with Trivy
        run: trivy sbom sbom.spdx.json --format json > trivy.json

      - name: Upload Trivy Result
        uses: actions/upload-artifact@v4
        with:
          name: trivy-result
          path: trivy.json
