name: SBOM Generation

on:
  pull_request:
    paths:
      - 'charts/**'   # Only run when Helm charts change

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh

      - name: Generate SBOM
        run: |
          syft dir:./charts/myapp -o json > sbom.json
          echo "SBOM generated at sbom.json"

      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: sbom.json

