name: SBOM + Trivy Scan

on:
  pull_request:
    paths:
      - 'charts/**'   # Only run when Helm charts change

jobs:
  sbom-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Syft
        run: |
          mkdir -p "$HOME/.local/bin"
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh \
            | sh -s -- -b "$HOME/.local/bin"
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"
        syft version


      - name: Generate SBOM
        run: |
          syft dir:./charts/myapp -o json > sbom.json
          echo "SBOM generated at sbom.json"

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh

      - name: Run Trivy Scan on SBOM
        run: |
          ./trivy sbom sbom.json --format json --output trivy_report.json
          echo "Trivy scan complete. Report saved to trivy_report.json"

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            sbom.json
            trivy_report.json

