name: Trivy Scan Caching Test
on:
  workflow_dispatch:

jobs:
  # 1) Uncached baseline
  scan_nocache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Trivy (no cache)
        id: nocache
        uses: aquasecurity/trivy-action@0.32.0
        with:
          image-ref: nginx:latest
          format: json
          output: trivy-nocache.json
          vuln-type: 'os,library'
          ignore-unfixed: false
        env:
          # force Trivy to download DB freshly into a temp dir so we don't benefit from cache
          TRIVY_CACHE_DIR: ${{ runner.temp }}/trivy-cache
      - name: Record duration
        if: always()
        run: |
          echo "nocache_duration_seconds=${{ steps.nocache.outputs.duration }}" >> $GITHUB_OUTPUT
        shell: bash

  # 2) Cached run
  scan_cached:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Restore Trivy DB cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: trivy-db-${{ runner.os }}
          restore-keys: |
            trivy-db-
      - name: Run Trivy (cached)
        id: cached
        uses: aquasecurity/trivy-action@0.32.0
        with:
          image-ref: nginx:latest
          format: json
          output: trivy-cached.json
          vuln-type: 'os,library'
          ignore-unfixed: false
      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trivy-outputs
          path: |
            trivy-nocache.json
            trivy-cached.json
